alter table public.pmo_user_directory
  add column if not exists home_latitude numeric(9,6),
  add column if not exists home_longitude numeric(9,6),
  add column if not exists home_radius_m integer not null default 500 check (home_radius_m between 50 and 5000);

create table if not exists public.pmo_report_location_events (
  id bigint generated by default as identity primary key,
  user_key text not null references public.pmo_user_directory(user_key) on update cascade on delete restrict,
  report_reference text,
  customer text,
  report_date date,
  report_success boolean not null,
  occurred_at timestamptz not null default now(),
  latitude numeric(9,6), longitude numeric(9,6), location_accuracy_m numeric(10,2),
  location_status text not null,
  distance_to_home_m numeric(12,2),
  within_home_radius boolean,
  verification_status text not null,
  source text not null default 'pmo-front'
);

create index if not exists pmo_report_location_events_user_time_idx
  on public.pmo_report_location_events (user_key, occurred_at desc);
alter table public.pmo_report_location_events enable row level security;
revoke all on table public.pmo_report_location_events from public, anon, authenticated;

create or replace function public.record_pmo_report_location(
  identity_key text, report_ref text, report_customer text, reported_date date,
  was_successful boolean, client_latitude numeric, client_longitude numeric,
  client_accuracy_m numeric, client_location_status text
)
returns void language plpgsql security definer set search_path = public as $$
declare
  home_lat numeric; home_lon numeric; radius_m integer;
  distance_m numeric; verification text; within_radius boolean;
begin
  select home_latitude, home_longitude, home_radius_m into home_lat, home_lon, radius_m
    from public.pmo_user_directory where user_key = identity_key;
  if client_location_status <> 'granted' then verification := client_location_status;
  elsif client_accuracy_m is null or client_accuracy_m > 500 then verification := 'low_accuracy';
  elsif home_lat is null or home_lon is null then
    update public.pmo_user_directory
      set home_latitude = client_latitude,
          home_longitude = client_longitude,
          home_radius_m = 500,
          updated_at = now()
      where user_key = identity_key;
    distance_m := 0;
    within_radius := true;
    verification := 'reference_auto_created';
  else
    distance_m := 6371000 * 2 * asin(sqrt(
      power(sin(radians((client_latitude - home_lat) / 2)), 2) +
      cos(radians(home_lat)) * cos(radians(client_latitude)) *
      power(sin(radians((client_longitude - home_lon) / 2)), 2)
    ));
    within_radius := distance_m <= radius_m;
    verification := case when within_radius then 'within_home_radius' else 'outside_home_radius' end;
  end if;
  insert into public.pmo_report_location_events (
    user_key, report_reference, customer, report_date, report_success,
    latitude, longitude, location_accuracy_m, location_status,
    distance_to_home_m, within_home_radius, verification_status
  ) values (
    identity_key, nullif(report_ref, ''), nullif(report_customer, ''), reported_date, was_successful,
    client_latitude, client_longitude, client_accuracy_m, client_location_status,
    distance_m, within_radius, verification
  );
end; $$;

revoke all on function public.record_pmo_report_location(text, text, text, date, boolean, numeric, numeric, numeric, text) from public, anon, authenticated;
grant execute on function public.record_pmo_report_location(text, text, text, date, boolean, numeric, numeric, numeric, text) to service_role;
