create table if not exists public.pmo_user_directory (
  user_key text primary key,
  external_user_id text,
  email text not null,
  full_name text not null,
  user_role text,
  status text not null default 'active' check (status in ('active', 'inactive', 'blocked')),
  first_login_at timestamptz not null default now(),
  last_login_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists pmo_user_directory_email_idx
  on public.pmo_user_directory (lower(email));

create table if not exists public.pmo_login_events (
  id bigint generated by default as identity primary key,
  user_key text not null references public.pmo_user_directory(user_key) on update cascade on delete restrict,
  event_type text not null default 'login' check (event_type in ('login')),
  occurred_at timestamptz not null default now(),
  user_agent text,
  source text not null default 'pmo-front'
);

create index if not exists pmo_login_events_user_time_idx
  on public.pmo_login_events (user_key, occurred_at desc);

alter table public.pmo_user_directory enable row level security;
alter table public.pmo_login_events enable row level security;

-- Solo las funciones de servidor pueden consultar o modificar el directorio y la auditoría.
revoke all on table public.pmo_user_directory from public, anon, authenticated;
revoke all on table public.pmo_login_events from public, anon, authenticated;

create or replace function public.record_pmo_login(
  identity_key text,
  identity_external_id text,
  identity_email text,
  identity_name text,
  identity_role text,
  client_user_agent text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.pmo_user_directory (
    user_key, external_user_id, email, full_name, user_role, status,
    first_login_at, last_login_at, created_at, updated_at
  ) values (
    identity_key,
    nullif(identity_external_id, ''),
    lower(identity_email),
    coalesce(nullif(identity_name, ''), lower(identity_email)),
    nullif(identity_role, ''),
    'active',
    now(), now(), now(), now()
  )
  on conflict (user_key) do update set
    external_user_id = coalesce(excluded.external_user_id, public.pmo_user_directory.external_user_id),
    email = excluded.email,
    full_name = excluded.full_name,
    user_role = coalesce(excluded.user_role, public.pmo_user_directory.user_role),
    last_login_at = now(),
    updated_at = now();

  insert into public.pmo_login_events (user_key, event_type, occurred_at, user_agent, source)
  values (identity_key, 'login', now(), nullif(left(client_user_agent, 500), ''), 'pmo-front');
end;
$$;

revoke all on function public.record_pmo_login(text, text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.record_pmo_login(text, text, text, text, text, text) to service_role;
