delete from public.pmo_field_options
where field_key in ('causa', 'prefijo', 'categoria', 'equipo', 'modoActuacion', 'lenguaje', 'objetoRicef');

insert into public.pmo_field_options (field_key, option_value, option_label, sort_order, is_default) values
  ('causa','Garantia','Garantia',0,false),
  ('causa','Data Maestra','Data Maestra',1,false),
  ('causa','Falta Configuraion','Falta Configuraion',2,false),
  ('causa','EscenarioNoProbado','EscenarioNoProbado',3,false),
  ('causa','EscenarioNoContemplado','EscenarioNoContemplado',4,false),
  ('causa','Nueva Funcionalidad','Nueva Funcionalidad',5,true),
  ('causa','Administrativo','Administrativo',6,false),
  ('causa','Reunion','Reunion',7,false),
  ('prefijo','CH','CH',0,true),
  ('prefijo','SR','SR',1,false),
  ('prefijo','IN','IN',2,false),
  ('prefijo','Proyecto','Proyecto',3,false),
  ('categoria','Everest','Everest',0,false),
  ('categoria','Operacion','Operacion',1,true),
  ('categoria','Proyecto','Proyecto',2,false),
  ('categoria','Coordinacion','Coordinacion',3,false),
  ('equipo','Financiero','Financiero',0,false),
  ('equipo','Comercial','Comercial',1,true),
  ('equipo','Logistico','Logistico',2,false),
  ('equipo','PlaneacionDemanda','PlaneacionDemanda',3,false),
  ('equipo','Analitica','Analitica',4,false),
  ('equipo','Portales','Portales',5,false),
  ('equipo','Infraestructura','Infraestructura',6,false),
  ('modoActuacion','Basado-Datos-Integraciones','Basado-Datos-Integraciones',0,true),
  ('modoActuacion','Basado-Datos-Automatizacion','Basado-Datos-Automatizacion',1,false),
  ('modoActuacion','Basado-Datos-Analitica','Basado-Datos-Analitica',2,false),
  ('modoActuacion','OXDE','OXDE',3,false),
  ('modoActuacion','Transaccional','Transaccional',4,false),
  ('lenguaje','JavaScript','JavaScript',0,false),
  ('lenguaje','Java','Java',1,false),
  ('lenguaje','PHP','PHP',2,false),
  ('lenguaje','PullOvers','PullOvers',3,false),
  ('lenguaje','ABAP','ABAP',4,true),
  ('lenguaje','NODEjs','NODEjs',5,false),
  ('lenguaje','PO','PO',6,false),
  ('lenguaje','OData','OData',7,false),
  ('lenguaje','DataService','DataService',8,false),
  ('lenguaje','Strling','Strling',9,false),
  ('lenguaje','Python','Python',10,false),
  ('lenguaje','UiPath','UiPath',11,false),
  ('lenguaje','Agility','Agility',12,false),
  ('objetoRicef','Interfases','Interfases',0,false),
  ('objetoRicef','Reportes','Reportes',1,false),
  ('objetoRicef','Conversiones','Conversiones',2,false),
  ('objetoRicef','Enhacement','Enhacement',3,false),
  ('objetoRicef','Formularios','Formularios',4,false);
